name: Push Dependabot PRs

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: ["**"]

jobs:
    notify-template:
        runs-on: ubuntu-latest
        steps:
            - name: Post comment using GitHub CLI
              env:
               GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                gh issue comment 35 \
                --repo org/template-repo \
                --body "Dependabot PR in [${{ github.repository }}](${{ github.event.pull_request.html_url }})"
